DEBUG:root:[2020-01-20 12:37:15 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:10:50 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:11:34 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:12:09 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:13:15 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:13:36 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:13:42 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:14:28 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:15:47 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:17:20 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:17:41 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:17:59 Eastern Standard Time] Type OperationalError Exception: no such table: Users in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\userdb_class.py at line 114.
DEBUG:root:[2020-01-20 14:17:59 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 30.
DEBUG:root:[2020-01-20 14:18:20 Eastern Standard Time] Type OperationalError Exception: no such table: Users in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\userdb_class.py at line 114.
DEBUG:root:[2020-01-20 14:18:20 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 30.
DEBUG:root:[2020-01-20 17:01:29 Eastern Standard Time] Type TypeError Exception: 'User' object is not subscriptable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-20 17:03:02 Eastern Standard Time] Type AttributeError Exception: 'list' object has no attribute 'add' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 31.
DEBUG:root:[2020-01-20 17:04:34 Eastern Standard Time] Type TypeError Exception: 'User' object does not support indexing in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-20 17:05:38 Eastern Standard Time] Type TypeError Exception: 'User' object is not subscriptable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 37.
DEBUG:root:[2020-01-20 17:07:59 Eastern Standard Time] Type TypeError Exception: 'User' object is not subscriptable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-20 17:09:05 Eastern Standard Time] Type TypeError Exception: list indices must be integers or slices, not str in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-20 17:11:15 Eastern Standard Time] Type TypeError Exception: list indices must be integers or slices, not str in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 35.
DEBUG:root:[2020-01-20 17:14:34 Eastern Standard Time] Type TypeError Exception: 'User' object does not support indexing in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 35.
DEBUG:root:[2020-01-20 17:19:25 Eastern Standard Time] Type NameError Exception: name 'user' is not defined in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-20 17:24:01 Eastern Standard Time] Type TypeError Exception: 'User' object is not subscriptable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-20 17:25:14 Eastern Standard Time] Type TypeError Exception: 'User' object does not support indexing in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-20 17:25:35 Eastern Standard Time] Type TypeError Exception: 'User' object is not callable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-21 11:13:03 Eastern Standard Time] Type AttributeError Exception: module 'db' has no attribute 'get_user_by_id' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 47.
DEBUG:root:[2020-01-21 11:13:51 Eastern Standard Time] Type ValueError Exception: parameters are of unsupported type in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 160.
DEBUG:root:[2020-01-21 11:37:41 Eastern Standard Time] Type TypeError Exception: __init__() missing 6 required positional arguments: 'first_name', 'last_name', 'email', 'score', 'create_date', and 'comment' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 50.
DEBUG:root:[2020-01-21 11:41:49 Eastern Standard Time] Type TypeError Exception: __init__() missing 6 required positional arguments: 'first_name', 'last_name', 'email', 'score', 'create_date', and 'comment' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 51.
DEBUG:root:[2020-01-21 11:44:53 Eastern Standard Time] Type TypeError Exception: __init__() missing 6 required positional arguments: 'first_name', 'last_name', 'email', 'score', 'create_date', and 'comment' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 51.
DEBUG:root:[2020-01-21 11:47:35 Eastern Standard Time] Type TypeError Exception: list indices must be integers or slices, not str in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 52.
DEBUG:root:[2020-01-21 11:50:48 Eastern Standard Time] Type IntegrityError Exception: UNIQUE constraint failed: User.Email in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 116.
DEBUG:root:[2020-01-21 11:50:48 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 4 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 160.
DEBUG:root:[2020-01-21 11:50:48 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not callable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 51.
DEBUG:root:[2020-01-21 11:51:09 Eastern Standard Time] Type TypeError Exception: 'list' object is not callable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 51.
DEBUG:root:[2020-01-21 11:51:39 Eastern Standard Time] Type TypeError Exception: list indices must be integers or slices, not str in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 51.
DEBUG:root:[2020-01-21 12:06:41 Eastern Standard Time] Type TypeError Exception: list indices must be integers or slices, not str in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 53.
DEBUG:root:[2020-01-21 12:18:18 Eastern Standard Time] Type ValueError Exception: not enough values to unpack (expected 7, got 1) in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 51.
DEBUG:root:[2020-01-21 12:20:22 Eastern Standard Time] Type TypeError Exception: 'int' object is not subscriptable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 54.
DEBUG:root:[2020-01-21 12:21:44 Eastern Standard Time] Type TypeError Exception: 'int' object is not subscriptable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 54.
DEBUG:root:[2020-01-21 12:22:35 Eastern Standard Time] Type TypeError Exception: 'int' object is not subscriptable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 54.
DEBUG:root:[2020-01-21 12:24:00 Eastern Standard Time] Type TypeError Exception: __init__() missing 6 required positional arguments: 'first_name', 'last_name', 'email', 'score', 'create_date', and 'comment' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 51.
DEBUG:root:[2020-01-21 12:27:24 Eastern Standard Time] Type TypeError Exception: 'int' object is not subscriptable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 55.
DEBUG:root:[2020-01-21 12:49:49 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 24 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 291.
DEBUG:root:[2020-01-21 12:49:49 Eastern Standard Time] Type IntegrityError Exception: UNIQUE constraint failed: User.Email in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 116.
DEBUG:root:[2020-01-21 12:49:49 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 4 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 160.
DEBUG:root:[2020-01-21 12:49:49 Eastern Standard Time] Type TypeError Exception: type object argument after * must be an iterable, not NoneType in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 52.
DEBUG:root:[2020-01-21 12:50:52 Eastern Standard Time] Type TypeError Exception: list indices must be integers or slices, not str in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 293.
DEBUG:root:[2020-01-21 12:50:52 Eastern Standard Time] Type IntegrityError Exception: UNIQUE constraint failed: User.Email in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 116.
DEBUG:root:[2020-01-21 12:50:52 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 4 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 160.
DEBUG:root:[2020-01-21 12:50:52 Eastern Standard Time] Type TypeError Exception: type object argument after * must be an iterable, not NoneType in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 52.
DEBUG:root:[2020-01-21 12:50:58 Eastern Standard Time] Type TypeError Exception: list indices must be integers or slices, not str in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 293.
DEBUG:root:[2020-01-21 12:50:58 Eastern Standard Time] Type IntegrityError Exception: UNIQUE constraint failed: User.Email in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 116.
DEBUG:root:[2020-01-21 12:50:58 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 4 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 160.
DEBUG:root:[2020-01-21 12:50:58 Eastern Standard Time] Type TypeError Exception: type object argument after * must be an iterable, not NoneType in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 52.
DEBUG:root:[2020-01-21 12:52:04 Eastern Standard Time] Type TypeError Exception: list indices must be integers or slices, not str in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 293.
DEBUG:root:[2020-01-21 12:52:04 Eastern Standard Time] Type IntegrityError Exception: UNIQUE constraint failed: User.Email in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 116.
DEBUG:root:[2020-01-21 12:52:04 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 4 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 160.
DEBUG:root:[2020-01-21 12:52:04 Eastern Standard Time] Type TypeError Exception: type object argument after * must be an iterable, not NoneType in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 52.
DEBUG:root:[2020-01-21 12:54:08 Eastern Standard Time] Type IntegrityError Exception: UNIQUE constraint failed: User.Email in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 116.
DEBUG:root:[2020-01-21 12:54:08 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 4 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 160.
DEBUG:root:[2020-01-21 12:54:08 Eastern Standard Time] Type TypeError Exception: type object argument after * must be an iterable, not NoneType in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 52.
DEBUG:root:[2020-01-21 12:55:03 Eastern Standard Time] Type IntegrityError Exception: UNIQUE constraint failed: User.Email in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 116.
DEBUG:root:[2020-01-21 12:55:03 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 4 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 160.
DEBUG:root:[2020-01-21 12:55:03 Eastern Standard Time] Type TypeError Exception: type object argument after * must be an iterable, not NoneType in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 52.
DEBUG:root:[2020-01-21 12:55:48 Eastern Standard Time] Type IntegrityError Exception: UNIQUE constraint failed: User.Email in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 116.
DEBUG:root:[2020-01-21 12:55:48 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 4 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 160.
DEBUG:root:[2020-01-21 12:55:48 Eastern Standard Time] Type TypeError Exception: type object argument after * must be an iterable, not NoneType in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 52.
DEBUG:root:[2020-01-21 13:02:22 Eastern Standard Time] Type UnboundLocalError Exception: local variable 'new_user' referenced before assignment in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 55.
DEBUG:root:[2020-01-21 13:13:56 Eastern Standard Time] Type UnboundLocalError Exception: local variable 'new_user' referenced before assignment in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 57.
DEBUG:root:[2020-01-21 13:14:19 Eastern Standard Time] Type AttributeError Exception: 'list' object has no attribute 'comment' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 58.
DEBUG:root:[2020-01-21 13:15:04 Eastern Standard Time] Type AttributeError Exception: 'list' object has no attribute 'first_name' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 58.
DEBUG:root:[2020-01-21 13:24:13 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 24 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\db.py at line 182.
DEBUG:root:[2020-01-21 13:24:13 Eastern Standard Time] Type TypeError Exception: type object argument after * must be an iterable, not NoneType in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 50.
DEBUG:root:[2020-01-21 13:41:12 Eastern Standard Time] Type TypeError Exception: update_user() argument after * must be an iterable, not User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 64.
DEBUG:root:[2020-01-21 14:11:15 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 31.
DEBUG:root:[2020-01-21 14:56:11 Eastern Standard Time] Type TypeError Exception: 'module' object is not callable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 31.
DEBUG:root:[2020-01-21 15:11:17 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 142.
DEBUG:root:[2020-01-21 15:11:17 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-21 15:13:56 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 142.
DEBUG:root:[2020-01-21 15:13:56 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-21 15:15:23 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 143.
DEBUG:root:[2020-01-21 15:15:23 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-21 15:15:54 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 143.
DEBUG:root:[2020-01-21 15:15:54 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-21 15:16:17 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 144.
DEBUG:root:[2020-01-21 15:16:17 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-21 15:16:43 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 143.
DEBUG:root:[2020-01-21 15:16:43 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-21 15:17:01 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 144.
DEBUG:root:[2020-01-21 15:17:01 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-21 15:17:44 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 145.
DEBUG:root:[2020-01-21 15:17:44 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 36.
DEBUG:root:[2020-01-21 15:21:40 Eastern Standard Time] Type NameError Exception: name 'create_user_table' is not defined in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 52.
DEBUG:root:[2020-01-21 15:21:40 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 140.
DEBUG:root:[2020-01-21 15:21:40 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 35.
DEBUG:root:[2020-01-21 15:22:22 Eastern Standard Time] Type NameError Exception: name 'create_user_table' is not defined in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 53.
DEBUG:root:[2020-01-21 15:22:22 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 141.
DEBUG:root:[2020-01-21 15:22:22 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 35.
DEBUG:root:[2020-01-21 15:24:41 Eastern Standard Time] Type NameError Exception: name 'create_user_table' is not defined in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 53.
DEBUG:root:[2020-01-21 15:24:41 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 141.
DEBUG:root:[2020-01-21 15:24:41 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 35.
DEBUG:root:[2020-01-21 15:26:12 Eastern Standard Time] Type NameError Exception: name 'create_user_table' is not defined in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 52.
DEBUG:root:[2020-01-21 15:26:12 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 140.
DEBUG:root:[2020-01-21 15:26:12 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 35.
DEBUG:root:[2020-01-21 15:26:43 Eastern Standard Time] Type NameError Exception: name 'create_user_table' is not defined in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 52.
DEBUG:root:[2020-01-21 15:26:43 Eastern Standard Time] Type OperationalError Exception: no such table: User in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 141.
DEBUG:root:[2020-01-21 15:26:43 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 35.
DEBUG:root:[2020-01-22 01:14:30 Eastern Standard Time] Type TypeError Exception: list indices must be integers or slices, not str in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 270.
DEBUG:root:[2020-01-22 23:18:51 Eastern Standard Time] Type AttributeError Exception: 'int' object has no attribute 'is_integer' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:22:42 Eastern Standard Time] Type RecursionError Exception: maximum recursion depth exceeded in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:23:31 Eastern Standard Time] Type RecursionError Exception: maximum recursion depth exceeded in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:24:17 Eastern Standard Time] Type RecursionError Exception: maximum recursion depth exceeded in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:25:15 Eastern Standard Time] Type RecursionError Exception: maximum recursion depth exceeded in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:27:05 Eastern Standard Time] Type RecursionError Exception: maximum recursion depth exceeded in comparison in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:27:34 Eastern Standard Time] Type RecursionError Exception: maximum recursion depth exceeded in comparison in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:28:12 Eastern Standard Time] Type Exception Exception: Invalid User ID. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:29:21 Eastern Standard Time] Type RecursionError Exception: maximum recursion depth exceeded in comparison in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:31:04 Eastern Standard Time] Type RecursionError Exception: maximum recursion depth exceeded in comparison in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:33:09 Eastern Standard Time] Type RecursionError Exception: maximum recursion depth exceeded in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:39:31 Eastern Standard Time] Type Exception Exception: Invalid User ID. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:46:00 Eastern Standard Time] Type NameError Exception: name 'user_id' is not defined in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-22 23:46:52 Eastern Standard Time] Type Exception Exception: Invalid first name. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 72.
DEBUG:root:[2020-01-23 00:07:00 Eastern Standard Time] Type ValueError Exception: First name cannot be empty or contain illegal characters. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:10:09 Eastern Standard Time] Type ValueError Exception: First name cannot be empty or contain illegal characters. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 72.
DEBUG:root:[2020-01-23 00:10:44 Eastern Standard Time] Type ValueError Exception: First name cannot be empty or contain illegal characters. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:10:58 Eastern Standard Time] Type ValueError Exception: First name cannot be empty or contain illegal characters. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:11:17 Eastern Standard Time] Type ValueError Exception: First name cannot be empty or contain illegal characters. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:11:53 Eastern Standard Time] Type ValueError Exception: First name cannot be empty or contain illegal characters. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:14:04 Eastern Standard Time] Type ValueError Exception: Score cannot be empty and must be equal to or between 0.0 and 100.0 in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 72.
DEBUG:root:[2020-01-23 00:14:26 Eastern Standard Time] Type ValueError Exception: Score cannot be empty and must be equal to or between 0.0 and 100.0 in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:14:36 Eastern Standard Time] Type ValueError Exception: Score cannot be empty and must be equal to or between 0.0 and 100.0 in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:15:47 Eastern Standard Time] Type ValueError Exception: Score cannot be empty and must be equal to or between 0.0 and 100.0 in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:26:51 Eastern Standard Time] Type ValueError Exception: Creation date cannot be empty or incorrectly formatted. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:27:18 Eastern Standard Time] Type ValueError Exception: Creation date cannot be empty or incorrectly formatted. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:27:50 Eastern Standard Time] Type TypeError Exception: object of type '_sre.SRE_Pattern' has no len() in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:29:37 Eastern Standard Time] Type ValueError Exception: Score cannot be empty and must be equal to or between 0.0 and 100.0 in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 38.
DEBUG:root:[2020-01-23 00:46:02 Eastern Standard Time] Type ValueError Exception: Email cannot be empty, incorrectly formatted,or contain illegal characters. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 72.
DEBUG:root:[2020-01-23 16:02:13 Eastern Standard Time] Type NameError Exception: name 'sqlite3' is not defined in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 30.
DEBUG:root:[2020-01-25 12:56:58 Eastern Standard Time] Type NameError Exception: name 'null' is not defined in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 57.
DEBUG:root:[2020-01-25 12:57:15 Eastern Standard Time] Type AttributeError Exception: 'sqlite3.Cursor' object has no attribute 'lastRowID' in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 97.
DEBUG:root:[2020-01-25 12:57:15 Eastern Standard Time] Type ProgrammingError Exception: Incorrect number of bindings supplied. The current statement uses 1, and there are 4 supplied. in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\database_functions.py at line 139.
DEBUG:root:[2020-01-25 12:57:15 Eastern Standard Time] Type Exception Exception: Cannot retrieve user data! in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 74.
